import { Memory } from '../types';

export const MOCK_MEMORIES: Memory[] = [
  {
    id: 'mock_1',
    title: 'The Great Pilsen Mural Walk',
    story: 'Back in the 90s, when my grandfather moved here, he helped paint one of the murals on 18th Street. Every time I walk past the vibrant facade of the Cooper Cooperative, I still see his signature stroke of teal on the corner of the wall. It connects me directly to our roots.',
    neighborhood: 'Lower West Side',
    era: '1990s',
    category: 'Culture',
    author: 'Elena Gomez',
    authorId: 'mock_author_1',
    timestamp: '2026-05-18T10:30:00Z',
    coordinates: [41.8576, -87.6652],
    isUnlocked: true,
    address: '1834 S Blue Island Ave, Chicago, IL',
    reactions: 28
  },
  {
    id: 'mock_2',
    title: 'Midnight Jazz session at Green Mill',
    story: 'Sitting in the same booth Al Capone once occupied, sipping a gin fizz, listening to a local trumpet player absolutely dominate the stage. There is something about the velvet-draped, neon-lit room that freezes time. Uptown at 2 AM is pure magic.',
    neighborhood: 'Uptown',
    era: '1970s',
    category: 'Music',
    author: 'Marcus Vance',
    authorId: 'mock_author_2',
    timestamp: '2026-05-15T02:15:00Z',
    coordinates: [41.9692, -87.6599],
    isUnlocked: true,
    address: '4802 N Broadway, Chicago, IL',
    reactions: 42
  },
  {
    id: 'mock_3',
    title: 'Harold’s Chicken No. 88 Run',
    story: 'Six wings, mild sauce on the fries, white bread soaked in grease. It was our post-high school ritual every single Friday after the football game. We’d sit on the trunk of my beat-up sedan in the gravel parking lot, debating if we’d ever make it big outside of the South Side.',
    neighborhood: 'South Shore',
    era: '2000s',
    category: 'Food',
    author: 'Darnell Jefferson',
    authorId: 'mock_author_3',
    timestamp: '2026-05-10T19:40:00Z',
    coordinates: [41.7648, -87.5752],
    isUnlocked: true,
    address: '1752 E 71st St, Chicago, IL',
    reactions: 56
  },
  {
    id: 'mock_4',
    title: 'First snow on Wicker Park Fountain',
    story: 'I remember our first winter living in Chicago. It was November, and the fountain in the heart of Wicker Park was finally turned off. Giant, heavy snowflakes began falling from a lavender sky, perfectly blanketing the stone structures. We shared a thermos of cocoa right there on the iron bench.',
    neighborhood: 'West Town',
    era: '2010s',
    category: 'Childhood',
    author: 'Chloe & Ben',
    authorId: 'mock_author_4',
    timestamp: '2026-04-30T16:05:00Z',
    coordinates: [41.9103, -87.6742],
    isUnlocked: true,
    address: '1425 N Damen Ave, Chicago, IL',
    reactions: 19
  },
  {
    id: 'mock_5',
    title: 'The Maxwell Street Market Blues',
    story: 'Before it was moved and downsized, Sunday morning meant Maxwell Street. You could smell the polish sausage with charred onions from blocks away. Blues guitarists plugged their amps into dynamic makeshift setups on the sidewalk. Best street vibe this city ever possessed.',
    neighborhood: 'Near West Side',
    era: '1980s',
    category: 'Local History',
    author: 'Robert "Blue" Montgomery',
    authorId: 'mock_author_5',
    timestamp: '2026-05-01T08:00:00Z',
    coordinates: [41.8643, -87.6436],
    isUnlocked: true,
    address: '800 W Maxwell St, Chicago, IL',
    reactions: 35
  },
  {
    id: 'mock_6',
    title: 'Logan Square Skatepark Sessions',
    story: 'Skating under the overpass by Logan Boulevard, scraping knees and learning kickflips with a boombox blasting local underground punk tapes. We spent whole summers there, just absorbing the graffiti walls and watching the Blue Line rattle by over our heads.',
    neighborhood: 'Logan Square',
    era: '2010s',
    category: 'Nightlife',
    author: 'Julian Reed',
    authorId: 'mock_author_6',
    timestamp: '2026-05-19T23:50:00Z',
    coordinates: [41.9298, -87.7081],
    isUnlocked: true,
    address: '2430 N Sacramento Ave, Chicago, IL',
    reactions: 24
  },
  {
    id: 'mock_7',
    title: 'Late Night Diner Chats at Tempo',
    story: 'Tempo Diner was the ultimate nightlife beacon. At 3:30 AM, after leaving the clubs on Rush Street, the booth would feel like an absolute sanctuary. We shared massive Spanish Omelettes and talked about everything from existential philosophy to who would pay the metro fare.',
    neighborhood: 'Near North Side',
    era: '1990s',
    category: 'Nightlife',
    author: 'Sarah Jenkins',
    authorId: 'mock_author_7',
    timestamp: '2026-05-17T03:45:00Z',
    coordinates: [41.8995, -87.6258],
    isUnlocked: true,
    address: '6 E Chestnut St, Chicago, IL',
    reactions: 31
  },
  {
    id: 'mock_8',
    title: 'U of C Regenstein Library All-nighter',
    story: 'Preparing for final thesis defense in the brutalist basement of "The Reg". The concrete walls felt heavy, but we snuck out to the quad at 4 AM to watch the sunrise silhouette the Gothic towers of Cobb Hall. High stress, but unforgettable camaraderie.',
    neighborhood: 'Hyde Park',
    era: '2010s',
    category: 'Student Life',
    author: 'Danielle Choi',
    authorId: 'mock_author_8',
    timestamp: '2026-05-12T04:10:00Z',
    coordinates: [41.7915, -87.5996],
    isUnlocked: true,
    address: '1100 E 57th St, Chicago, IL',
    reactions: 15
  },
  {
    id: 'mock_9',
    title: 'The Great Loop Alleyway Discovery',
    story: 'I got lost looking for a shortcut to the Auditorium Theatre. Stumbled into an old loading alleyway and saw a brass architectural element dating back to the late 1800s. Realized Chicago has multiple layers, some pristine, some completely forgotten in shadow.',
    neighborhood: 'Loop',
    era: '1960s',
    category: 'Local History',
    author: 'Arthur Pendelton',
    authorId: 'mock_author_9',
    timestamp: '2026-05-05T14:22:00Z',
    coordinates: [41.8758, -87.6251],
    isUnlocked: true,
    address: '50 E Congress Pkwy, Chicago, IL',
    reactions: 48
  },
  {
    id: 'mock_10',
    title: 'Bridgeport Paletero Bells',
    story: 'The most beautiful sound of a hot July afternoon was the ringing of bells from the paletero cart coming down Morgan Street. We would run down the stairs with sticky quarters clutched in our hands, eager to buy lime and mango water-based ice bars.',
    neighborhood: 'Bridgeport',
    era: '2000s',
    category: 'Childhood',
    author: 'Mateo Ortiz',
    authorId: 'mock_author_10',
    timestamp: '2026-05-19T14:00:00Z',
    coordinates: [41.8364, -87.6487],
    isUnlocked: true,
    address: '3200 S Morgan St, Chicago, IL',
    reactions: 27
  },
  {
    id: 'mock_11',
    title: 'Rainy afternoon at Myopic Books',
    story: 'Spending three solid hours lost in the narrow, creaky mazes of Myopic. The smell of aged paper, a gentle hum of rain on the roof, and finding a signed poetry chapbook from a local author in a dusty corner. Wicker Park at its purest.',
    neighborhood: 'West Town',
    era: '2000s',
    category: 'Culture',
    author: 'Lillian Fowler',
    authorId: 'mock_author_11',
    timestamp: '2026-05-18T15:30:00Z',
    coordinates: [41.9105, -87.6775],
    isUnlocked: true,
    address: '1564 N Milwaukee Ave, Chicago, IL',
    reactions: 39
  },
  {
    id: 'mock_12',
    title: 'Argyle Street Lunar New Year Parade',
    story: 'My family moved to Uptown from Vietnam in 1982. This parade was the event where the community came together to dance, set off firecrackers, and share banh mi. It felt like establishing our voice in a brand new, colder world.',
    neighborhood: 'Uptown',
    era: '1980s',
    category: 'Immigration',
    author: 'Tuan Nguyen',
    authorId: 'mock_author_12',
    timestamp: '2026-05-11T11:00:00Z',
    coordinates: [41.9733, -87.6593],
    isUnlocked: true,
    address: '1100 W Argyle St, Chicago, IL',
    reactions: 51
  }
];
